name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies and build
      run: |
        npm install
        npx webpack

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name "matalvarez10"
        git config --global user.email "matias.alvarezc@utem.cl"
        echo 'your-repo-name.github.io' > dist/CNAME
        git add dist
        git commit -m "Deploy to GitHub Pages"
        git subtree split --prefix dist -b gh-pages
        git push -f origin gh-pages
